# Generated by Django 5.2.4 on 2025-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
